name: Generic-CI
on:
  workflow_dispatch:
    
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout

jobs:
  ci:
    uses: cdornele/terraform-modules-ci/.github/workflows/ci-tf-modules.yml@development