name: Generic-CI
on:
  workflow_dispatch:

permissions:
  contents: write  # This is required for actions/checkout

jobs:
  ci:
    uses: cdornele/terraform-modules-ci/.github/workflows/ci-tf-modules.yml@development