name: Generic-CI
on:
  workflow_dispatch:

permissions:
  contents: write
  security-events: write
  actions: read

jobs:
  ci:
    uses: cdornele/terraform-modules-ci/.github/workflows/ci-tf-modules.yml@development